language: java
jdk:
 - oraclejdk8
dist: trusty
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
deploy:
 provider: heroku
 api-key: 
  secure: qu4qZ3/KrTJNZCiSfuPaaYh1eUQj54wvnCFa1255m/+fIeU+GwJ+gEIrHMU9HvlptG9dfCGk87V1O6FkEZJcMWQgMY2lHecE0vMB3Jmwd/ExktGgI2HXRBANwj8Xvdp0SUUPKfMefCjCIUVb9o8vun5S2cB9Vqjhh0/pYbxiR4/VjCpsgY2YxSr3EivhV4msuuht5Wiw4LXfOrFpD7EgwWeEZbZQaQi4vXm2jeZDhyEsph5CPwiI2g3Z+FG3GHA23DNiICDrhTehWZA1/TR4fai5xycOS/9q/BlrD5jwMWZAa83QKWeBVgChv0N34lHeCwhfubIKOyCXy4BcV4H4Af/y83ic2N2KvEP/QQPD/6ir4BWATN44rXC1JC8mfCVE2FDzTGUjGIR6w5kQ/5xw5bPIbCHKvi179NEm32ZYOoVt7TBrTAgWFjb84lRncT96iBfaVW4Cz1v/EcFr4dJ4FuNKT8vM00gWw9az3aKxhKe0i8Q9Slrwm2Gkaj/9rKSa33k7CIa5cNsaUzT6Pq1RECSfh/9RN3T/4OUzMjNyWj5kXMtC/lyVqBycanaMb3hPCYVoc4Ov7kY1OneZoPtT0pZnwimR/1icSTXxqQBs74LrPhF72q9xoPnYxk3R+8v50BholOlXFzgOd4IeTxoVIJpTAjOp0JbOFpRRbevmjwM=
 app: fastyle
 edge: true
addons:
  sonarqube:
    organization: "fastyle"
    token:
      secure: acqNHHriZiTeFa4iJuXYcU4YQvvAlvjZ+ZcxJJHUXIw8dyaGw73C7X6M492HBaHHFM7c2QoO/pDZR8bAGPiixA3RrAp00nSgKxeYKtFMOIfSR3+V1x6C+l73qQtH85FZSTeI4DYhjzh24GGUiyOo39bMolA8B7/A64gfqNWdC/+eEIrwRXyYRvBTY6+B95bzZtkfavEaTGSQZ0H+7qiSiyUaI+Opv4OOJiLeVNi4ytqCuVkCgJ6g/I2tEGkX/zeYB82jtfbWrpep8rUxhRwzHzCXMGQw7kRY8vk8u5EZpVYqUvo/8mPad0ANNlvxuhxVV6q3N0iOl5TCRae/hTPXYlD+83ebHht1W1yNKukIT7KCeB3+ARuwqhtZjGt5VP7KLo/TqNCFRFIkwUerB7tZlurcGIFu94WMNZMnN4bIPLqJr7a6hXFAbUwyVKu7BzXE+S546Nhr5HMgE2k4LHmeKo0U78qsy0L/AX7jzA+t6bYbHcW6AQUzR9/3yR4qsFg1y3bTsN7/VQJ7PhMb8d5FQYmU8d3wz8u3ZbT+AeHXJmaf+abHKi58HvQCD+rAgQu3bglaKcNx151FKs73aO8eGw3lbbOPqyt/K+GAhRJOuFJHicou4R42AZBwyeAKBgT/3m7w6NFja0geLmfc1LPHR1tG/o+x095Wk+3ZUHoCmYQ=
script:
  - sonar-scanner
