language: java
jdk:
 - oraclejdk8
dist: trusty
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
deploy:
 provider: heroku
 api-key: 
  secure: 8486bcc9-267c-4f21-abad-a03a3365ecd9
 app: fastyle
 edge: true